
"""
Run everything together

WARNING THIS COULD TAKE DAYS.
RECCOMMENDED USE IS TO TAKE ONE EXPERIMENT FROM THE EXPERIMENTS PACKAGE AND RUN IT.
THIS FILE RUNS EVERYTHING I DID THROUGHOUT THE PROJECT ALL AT ONCE
"""

def main():
    pass


if __name__ == '__main__':
    main()
